name: 'Deploy MSSQL Server'
run-name: '${{ github.actor }} - Deployingto_${{ github.event.inputs.subscription }}_${{ github.event.inputs.environment }}'
on:
  workflow_dispatch:
    inputs:
      requesttype:
        type: choice
        description: "Request Type"
        required: true
        options:
          - "Create (with New RG)"
          - "Create (with Existing RG)"
          - "Remove"
        default: "Create (with New RG)"
      subscription:
        type: string
        description: "Please enter your subscription Name"
        required: true
      location_pair:
        type: choice
        description: "Choose a JSON array of two Azure regions (first = primary, second = secondary)."
        required: true
        options:
          - '["eastus2","centralus"]'
          - '["centralus","eastus2"]'
      environment:
        type: choice
        description: "Choose the environment"
        options:
          - dev
          - qa
          - UAT
          - Prod
      purposeRG:
        type: string
        description: "Resource Group Purpose.......... Hyphen designate an existing RG"
        required: true
      purpose:
        type: string
        description: "purpose/sequence"
        required: true
      subnetname:
        type: string
        description: "Enter the subnet name for db endpoints"
        required: true
      dbcollation:
        type: string
        description: "Specify Collation of the database"
        required: false
        default: SQL_Latin1_General_CP1_CI_AS
      skuname:
        type: choice
        description: "Select SKU_NAME used by Database"
        options:
          - S0
          - P2
          - Basic
          - ElasticPool
          - BC_Gen5_2
          - HS_Gen4_1
          - GP_S_Gen5_2
          - DW100c
          - DS100
      zoneredundancy:
        type: choice
        description: "Zone Redundancy"
        required: true
        options:
          - "false"
          - "true"

jobs:
  mysql-server_new_rg:
    if: ${{ github.event.inputs.requesttype == 'Create (with New RG)' }}
    name: 'Deploying - MSSQL server (New RG)'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy MSSQL Server
        uses: ./.github/workflows/Createmssqlserver.yml
        with:
          name: 'mssql'
          subscription: '${{ github.event.inputs.subscription }}'
          location: '${{ fromJson(github.event.inputs.location_pair)[0] }}'
          secondary_location: '${{ fromJson(github.event.inputs.location_pair)[1] }}'
          purposeRG: '${{ github.event.inputs.purposeRG }}'
          environment: '${{ github.event.inputs.environment }}'
          purpose: '${{ github.event.inputs.purpose }}'
          subnetname: '${{ github.event.inputs.subnetname }}'
          dbcollation: '${{ github.event.inputs.dbcollation }}'
          skuname: '${{ github.event.inputs.skuname }}'
          zoneredundancy: '${{ github.event.inputs.zoneredundancy }}'

  mysql-server_existing_rg:
    if: ${{ github.event.inputs.requesttype == 'Create (with Existing RG)' }}
    name: 'Deploying - MSSQL server (Existing RG)'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy MSSQL Server
        uses: ./.github/workflows/Createmssqlserver.yml
        with:
          name: 'mssql'
          subscription: '${{ github.event.inputs.subscription }}'
          location: '${{ fromJson(github.event.inputs.location_pair)[0] }}'
          secondary_location: '${{ fromJson(github.event.inputs.location_pair)[1] }}'
          purposeRG: '${{ github.event.inputs.purposeRG }}'
          environment: '${{ github.event.inputs.environment }}'
          purpose: '${{ github.event.inputs.purpose }}'
          subnetname: '${{ github.event.inputs.subnetname }}'
          dbcollation: '${{ github.event.inputs.dbcollation }}'
          skuname: '${{ github.event.inputs.skuname }}'
          zoneredundancy: '${{ github.event.inputs.zoneredundancy }}'

  mysql-server_remove:
    if: ${{ github.event.inputs.requesttype == 'Remove' }}
    name: 'Removing - MSSQL server'
    runs-on: ubuntu-latest
    steps:
      - name: Remove MSSQL Server
        uses: ./.github/workflows/Createmssqlserver.yml
        with:
          name: 'mssql'
          subscription: '${{ github.event.inputs.subscription }}'
          location: '${{ fromJson(github.event.inputs.location_pair)[0] }}'
          secondary_location: '${{ fromJson(github.event.inputs.location_pair)[1] }}'
          purposeRG: '${{ github.event.inputs.purposeRG }}'
          environment: '${{ github.event.inputs.environment }}'
          purpose: '${{ github.event.inputs.purpose }}'
          subnetname: '${{ github.event.inputs.subnetname }}'
          dbcollation: '${{ github.event.inputs.dbcollation }}'
          skuname: '${{ github.event.inputs.skuname }}'
          zoneredundancy: '${{ github.event.inputs.zoneredundancy }}'
